build:
  stage: build
  script:
    - make cppcheck
    - make cmake build
  artifacts:
    paths:
      - build/debug/*
      - build/release/*
  cache:
    paths:
      - laslib/LASlib/src/*.o
      - laslib/LASzip/src/*.o

test:
  stage: test
  script:
    - make test
    - make memcheck
