build:
  stage: build
  script:
    - make cmake compile
  artifacts:
    paths:
      - build/debug/*
      - build/release/*
  #cache:
  #  paths:
  #    - build/*

test:
  stage: test
  script:
    - make test
